### ISSUE TITLE
[publicodes-react] Les valeurs affichées sont arrondies à deux décimales

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#148]
Il faudrait : 
- afficher les valeurs exactes lorsque la valeur a été saisie manuellement dans la règle
- si un `arrondi` est présent sur la règle, afficher un nombre de décimales qui corresponde à celui donné en paramètre

**Comment by mquandalle** [comment]
J'ai vu par exemple que ça posait problème pour vérifier le paramètre T de la réduction générale ou lodéom, qui est donné sur le site de l'Urssaf avec 4 décimales.

**Comment by laem** [comment]
Je confirme le problème : l'arrondi actuel est bien trop important :) 

![image](https://user-images.githubusercontent.com/1177762/151337199-1e022402-6cfb-46c2-979f-c09f7dc2e5ee.png)

@johangirod je crois qu'il faut aussi gérer l'affichage quand la valeur décimale a un nombre infi de chiffres, du genre 1/3. 

Peut-être le restreindre à 3 décimales (toLocalseString(value, {maximumFractionDigits: 3}) ? 
avec un clic sur la valeur qui en affiche davantage ?

**Comment by mquandalle** [comment]
Il y a déjà une notion de "fullPrecision" au niveau des nœuds enfants

https://github.com/betagouv/publicodes/blob/4f5036aea3e0650dcf55877275ea5cf7dea5fc07/packages/react-ui/source/mecanisms/common.tsx#L27

https://publi.codes/studio?code=param%C3%A8tre+T%3A+0.12324+%2B+1 (0.1234 est affiché avec les 4 décimales).

Peut-être que les mécanismes sommes et produit devrait aussi inférer le nombre de “chiffres significatifs” comme dans nos exercices de physique au lycée.
