### ISSUE TITLE
Memory leak in shallowCopy()

### ISSUE THREAD

**Issue by wiinxt** [publicodes/publicodes#239]
Dans l'api nous utilisons `shallowCopy()` pour chaque nouvelle requête à `/evaluate`, cela cause une fuite de mémoire qui finit par faire crash l'instance Scalingo.
Le problème viens du fait qu'on garde une référence de chaque Engine créée dans le tableau `subEngines`
https://github.com/betagouv/publicodes/blob/e1fc6428605f52c0ecbc77b84ecda919fa3b779f/packages/core/source/index.ts#L270

J'ai fait un fix temporaire coté api avec un `originalEngine.subEngines = []` juste après le `originalEngine.shallowCopy()`

**Comment by mquandalle** [comment]
Pour le contexte c'est moi qui avait ajouté cette liste de `subEngines` dans https://github.com/betagouv/mon-entreprise/pull/1800 tout en me disant que le concept n'était pas génial. Le besoin est de pouvoir explorer l'intérieur des `recalcul` et `inversion` via des références sérialisables pour une règle `x` à l'intérieur du recalcul `y`.

#92 est une solution possible, l'idée était d'utiliser `y . x` pour indiquer “la variable x dans le recalcul y” au lieu de `x?subEngine=y`.
