### ISSUE TITLE
Ajouter la possibilité de référencer une règle avec son chemin absolu

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#253]
### Problème

Il est impossible de désambiguïser la référence `salarié` dans la règle `salarié . cotisation` 'exemple suivant :

```yaml
salarié: CDI

salarié . cotisations: 
  applicable si: salarié = 'CDI'

salarié . cotisations . salarié: 50 €
 
```

### Solution
Pouvoir seulement référencer une règle en précisant son chemin absolu.
On peut imaginer la syntaxe `@ . salarié` ou juste `. salarié`. 

L'implémentation devrait être directe.

**Comment by mquandalle** [comment]
Je partage 2 solutions alternatives mais je préfère ton idée de chemin absolu :

- changer l'ordre de lecture des espaces de noms, `salarié` ferait par défaut référence à la règle de premier niveau, et il faudrait expliciter `cotisations . salarié` pour accéder à la règle enfant depuis `salarié . cotisations`
- chemin relatif au parent : `.. salarié`
