### ISSUE TITLE
Ajouter un warning quand une règle parente est manquante

### ISSUE THREAD

**Issue by wiinxt** [publicodes/publicodes#278]
Une règle sans parent comme `test . plop . plop` dans [cet exemple](https://publi.codes/studio/d%C3%A9penses-primeur?code=%0A%23+Bienvenue+dans+le+bac+%C3%A0+sable+du+langage+publicode+%21%0A%23+Pour+en+savoir+plus+sur+le+langage+%3A%0A%23+%3D%3E+https%3A%2F%2Fpubli.codes%2Fdocumentation%2Fprincipes-de-base%0A%0Aprix%3A%0A++avec%3A%0A++++carottes%3A+2%E2%82%AC%2Fkg%0A++++champignons%3A+5%E2%82%AC%2Fkg%0A++++avocat%3A+2%E2%82%AC%2Favocat%0A%0A%23+test%3A+oui%0A%23+test+.+plop%3A+oui%0Atest+.+plop+.+plop%3A+42%E2%82%AC%0A%0Ad%C3%A9penses+primeur%3A%0A++somme%3A%0A++++-+prix+.+carottes+*+1.5+kg%0A++++-+prix+.+champignons+*+500g%0A++++-+prix+.+avocat+*+3+avocat%0A++++-+test+.+plop+.+plop%0A) ne devrais pas être accepté par l'engine car elle l'a font crash quand on y accède : [exemple](https://publi.codes/studio/test/plop/plop?code=%0A%23+Bienvenue+dans+le+bac+%C3%A0+sable+du+langage+publicode+%21%0A%23+Pour+en+savoir+plus+sur+le+langage+%3A%0A%23+%3D%3E+https%3A%2F%2Fpubli.codes%2Fdocumentation%2Fprincipes-de-base%0A%0Aprix%3A%0A++avec%3A%0A++++carottes%3A+2%E2%82%AC%2Fkg%0A++++champignons%3A+5%E2%82%AC%2Fkg%0A++++avocat%3A+2%E2%82%AC%2Favocat%0A%0A%23+test%3A+oui%0A%23+test+.+plop%3A+oui%0Atest+.+plop+.+plop%3A+42%E2%82%AC%0A%0Ad%C3%A9penses+primeur%3A%0A++somme%3A%0A++++-+prix+.+carottes+*+1.5+kg%0A++++-+prix+.+champignons+*+500g%0A++++-+prix+.+avocat+*+3+avocat%0A++++-+test+.+plop+.+plop%0A).
Autre remarque ces règles ne sont pas accessible dans le menu de la doc

**Comment by mquandalle** [comment]
Alternative: accepter les parents manquants et considérer qu'ils sont implicitement comme des règles vides : 

```yaml
test . plop . plop: 5
```

équivaut sémantiquement à :

```yaml
test:
test . plop:
test . plop . plop: 3
```

Je n'ai pas de grosse conviction dans un sens ou dans l'autre mais peut-être que les parents facultatifs est plus agréable dans le studio quand on copie/colle des règles existantes.

**Comment by johangirod** [comment]
Oui, mais cela peut aboutir à des bugs liés à des renommages / des typos possiblement non détectés à la compilation.

Ou alors des warnings ?
Ou, dernière possibilité : un linter pour publicodes :)

**Comment by mquandalle** [comment]
> mais cela peut aboutir à des bugs liés à des renommages

hum je ne vois pas dans quel cas ?

**Comment by johangirod** [comment]
Ça m'est déjà arrivé dans le cas de refacto. Par exemple, j'ai renommé `protection sociale . santé` en `protection sociale . maladie`, et j'ai oublié de renommer `protection sociale . santé . indemnités`. L'erreur était silencieuse, c'est dommage. Il faut que l'on acte sur la direction que l'on souhaite donner à l'interpreteur publicodes : « forgiving » à la javascript (en comptant sur des outils externes comme des linter pour valider / ou des warnings) ou plus stricte comme les langages fortement typés. C'est la même question qui se pose pour le cas pour les erreurs d'unités (type).

La solution idéale selon moi, serait d'avoir des warnings à la compilation, avec la possibilité de passer le moteur en mode « strict » pour transformer les warnings en erreur.

**Comment by mquandalle** [comment]
Un exemple où le studio est indésirablement cassé à cause d'un parent, « ouvrir dans le studio » la doc https://mon-entreprise.urssaf.fr/documentation/SMIC/net-imposable

**Comment by johangirod** [comment]
Il y a bien une erreur déclenchée maintenant, qui peut être désactivée avec l'option `allowOrphanRules` du moteur.
