### ISSUE TITLE
Documentation de "une possibilité"

### ISSUE THREAD

**Issue by laem** [publicodes/publicodes#28]
Je vois que ce mécanisme qui n'en n'est pas un est marqué comme "va évoluer bientôt" dans betagouv/publicodes#27 
Mais en attendant, j'ai l'impression qu'il est nulle part dans la doc, or c'est une brique assez importante du langage. 

Notamment le fait de devoir spécifier une valeur par défaut de ce style me semble vraiment pas évident.

```yaml
par défaut: "'tulipe'"
```
Je pense qu'il faut l'ajouter, qu'en pensez-vous ?

**Comment by johangirod** [comment]
Le mécanisme a été supprimé de publicodes. Il reviendra lorsque nous travaillerons sur un type option.

**Comment by laem** [comment]
@johangirod marrant, je viens juste de tomber ici via une recherche et plusieurs sauts. 

Je dois justement intégrer une question à choix multiples dans ma nouvelle app, et je n'ai rien trouvé dans la doc. 

Ça vaut le coup je pense de documenter le sujet dans https://publi.codes/docs/guides/créer-formulaire. 

Je vais itérer de mon côté d'abord.

**Comment by laem** [comment]
Bon, je confirme que coder le système de "une / plusieurs possibiltés", qu'on appelle mosaïque chez NGC @Clemog @EmileRolley , c'est pas trivial. 

Au moins aussi compliqué que de faire le lot input text, nombre et binaires.

Car ça revient à faire des groupes de questions. 

D'où l'intérêt d'avoir un template :) J'ai toujours pas de code à ouvrir pour l'instant, mais ça viendra. Faut juste que je stoppe à temps avant que mon app devienne trop spécialisée.

**Comment by Clemog** [comment]
> Bon, je confirme que coder le système de "une / plusieurs possibiltés", qu'on appelle mosaïque chez NGC @Clemog @EmileRolley , c'est pas trivial.

On a une carte pour justement proposé d'ajouter dans la doc de Publicodes notre manière de gérer les mosaïques :)
