### ISSUE TITLE
Supprimer le paramètre `avec` dans le mécanisme `inversion numérique`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#321]
Ou si l'on ne souhaite pas introduire de "breaking", laisser la possibilité de ne pas le spécifier. Par ailleurs, laisser la possibilité de spécifier un scalaire lorsqu'il n'y a qu'une seule inversion possible (un principe du langage que l'on retrouve dans `remplace` par exemple).

```yaml
a:
  inversion numérique:
    avec: 
      - b
```

Version non breaking : 

```yaml
a:
  inversion numérique: b 
```

Version breaking : 

```yaml
a:
  inversion numérique avec: b 
```

**Comment by mquandalle** [comment]
Les deux me vont. Effectivement vu qu'il y a qu'un seul argument pas besoin d'introduire une sous-clé `avec`.
