### ISSUE TITLE
Rendre les espaces facultatifs avant/après + - * /

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#328]
Actuellement `1*1` provoque une erreur de syntaxe, cf. [studio](https://publi.codes/studio/d%C3%A9penses-primeur?code=prix%3A+1*1%0A)

**Comment by johangirod** [comment]
Nopnopnop : cela voudrait dire qu'on ne pourrait plus avoir de `-` dans les noms de variable publicodes (exemple : `auto-entrepreneur`). L'espace est un caractère structurant de la syntaxe publicodes, et ce n'est pas grave, tant que c'est clair.

- `a/b` est une unité mais `a / b` est une opération
- `a-b est une variable mais `a - b`
- dans la même lignée, on pourrait imager que `a * b` soit une opération et `a*b` un nom de variable.

**Comment by johangirod** [comment]
Après avoir des erreurs clairs du type  `est-ce que vous vouliez écrire 1 * 1 ?` serait un gros plus.
