### ISSUE TITLE
Empêcher les espaces dans le mécanisme `unités:` par cohérence avec l'écriture dans les expressions 

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#332]
Aujourd'hui le mécanisme `unité` accepte une écriture avec des espaces
```yaml
a:
  valeur: 4
  unité: € / jour
```

Hors l'écriture `inline` n'accepte que des unités sans espace : 
```yaml
a: 4 € / jour 
# ERREUR
```
```yaml
a: 4 €/jour 
# correct
```

Par soucis de consistance et de cohérence, je serai d'avis de déprécier l'écriture d'unité avec espace dans le mécanisme. Cela permettrait d'effectuer des recherches globales sur une unité par exemple.

**Comment by mquandalle** [comment]
Complètement d'accord.

Par cohérence la question se pose aussi dans l'UI de la doc React : 

![image](https://user-images.githubusercontent.com/1730702/206172665-3c9ad077-56ca-46d5-b375-0546d41d438b.png)
