### ISSUE TITLE
Enfants d'une règle `non applicable`

### ISSUE THREAD

**Issue by Clemog** [publicodes/publicodes#359]
Hello ! Je ne sais pas très bien s'il fallait faire une issue ou discussions.

Je voulais remonter un problème déjà remonté à plusieurs reprises mais de mon côté c'est très problématique:

Aujourd'hui, le mécanisme `non applicable` est designé de sorte que les enfants d'une règles `non applicable` devient non applicable également. Dans Nos Gestes Climat, on utilise énormément ce mécanisme et nous utilisons également beaucoup de règles dépendantes d'un mécanisme `non applicable` "ailleurs". 

Comme ici : https://publi.codes/studio/d#a%3A%0A%20%20applicable%20si%3A%20b%0A%20%20formule%3A%2010%0A%0Ab%3A%20non%0A%0Aa%20.%20c%3A%2010%0A%0Ad%3A%20a%20.%20c

Pour contourner ce pb, j'utilise en général des `variations` mais ce n'est pas idéal ..

https://publi.codes/studio/d#a%3A%0A%20%20formule%3A%0A%20%20%20%20variations%3A%0A%20%20%20%20%20%20-%20si%3A%20b%0A%20%20%20%20%20%20%20%20alors%3A%2010%0A%20%20%20%20%20%20-%20sinon%3A%200%0A%0Ab%3A%20non%0A%0Aa%20.%20c%3A%2010%0A%0Ad%3A%20a%20.%20c

Il me semble que dans l'historique, ce comportement a été implémenté assez "tard" et je me rends compte parfois d'erreur liées à ça dans nos actions.

Je ne retrouve pas les discussions sur le sujet, peut etre que ça a déjà été longuement débattu alors désolé pour le doublon.. Sinon je veux bien en discuter davantage pour voir comment améliorer ça ;)

ping @laem @johangirod

**Comment by johangirod** [comment]
C'est un comportement implémenté depuis très longtemps, à mon arrivée en 2018. L'idée originale était de simplifier la base de code qui contenait beaucoup de `applicable si: parent`. Cela nous semblait un ajout simple et facile pour éviter de se répéter. 

Mais, quelques années plus tard, je te rejoins sur le fait que ce comportement peut prêter à confusion. Par ailleurs, il nous a souvent gênés, @mquandalle et moi, lors de précédentes refacto.

Dans l'idée, je préfèrerais que le parent rende explicitement non applicable ses enfants. Ce serait un comportement plus clair, et moins surprenant. Pour ce faire, on pourrait imaginer étendre la syntaxe de `rend non applicable` avec des sélecteurs qui vise tous les enfants. Par exemple : 

```yaml
a:
  applicable si: b
  rend non applicable: a . *
```
ou encore

```yaml
a:
  applicable si: b
  rend non applicable: 
    toutes les règles de: a
```

Cela aurait l'avantage de résoudre le problème listé dans https://github.com/betagouv/publicodes/issues/206

Il y a néanmoins deux problèmes avec ce changement : 
1. C'est un gros changement cassant, qui suppose beaucoup de modifications assez fine des règles publicodes existantes pour ne pas engendrer de régressions. 
2. `rend non applicable` fonctionne comme le remplacement. Or les remplacements transitifs ne sont pas implémentés. Cela aboutirait à un bug dans le cas d'une règle rendue non applicable et remplacée. Il faudrait donc corriger #55 avant. 

En attendant, la solution intermédiaire est de déplacer les valeurs dans un autre espace de nom. C'est ce que l'on fait sur mon-entreprise.

**Comment by Clemog** [comment]
> C'est un comportement implémenté depuis très longtemps, à mon arrivée en 2018. L'idée originale était de simplifier la base de code qui contenait beaucoup de `applicable si: parent`.

Ah d'acc, je suis étonné car j'ai l'impression que le changement du comportement du `applicable si` était plus récent donc sorry :)

Merci pour #206 !

Je me demande juste pour quelle raison il a été décidé que toute la branche soit non applicable si le parent de ne l'est pas au départ ?

Je ne suis pas sur de bien comprendre tes 2 points

> En attendant, la solution intermédiaire est de déplacer les valeurs dans un autre espace de nom. C'est ce que l'on fait sur mon-entreprise.

Yes également !

**Comment by laem** [comment]
@Clemog est-ce que tu as un exemple plus complet, réel pour décrire le problème ?

Qu'est-ce que `c` ? Un facteur d'émission que tu as rangé dans l'espace de nom `voiture` mais que tu voudrais utiliser ailleurs ? 

Si c'est le cas, alors la solution la plus simple à mon avis serait de permettre un `fetch`. Quelle que soit la valeur de l'applicabilité évaluée, tu veux juste récupérer la valeur de l'enfant. 

En termes d'historique, je crois que ça a été décidé notamment pour alléger fortement le calcul : aucune raison de calculer les enfants d'un non applicable, c'est du temps perdu. 

Un `fetch` pourrait justement vouloir dire : `Certes toute la branche peut être non applicable, mais là j'ai besoin que tu évalues quand même juste cet enfant, indépendamment de l'applicabilité de ses parents`.

**Comment by laem** [comment]
Après, je suis plus au courant de l'implé actuelle, mais dans ton exemple initial, il semble que de toutes façon `c` est calculée. En tout cas son calcul s'affiche dans la doc. Donc il y aurait juste un blocage fait au niveau de l'appel de `a . c` qui retourne `non applicable` car `a` l'est ? Dans ce cas là l'appel via un mécanisme ferait l'affaire sans trop de changements. 

```yaml
a:
  applicable si: b
  formule: 10

b: non

a . c: 23 + 6

d: 
  valeur isolée: a . c
```

**Comment by Clemog** [comment]
> @Clemog est-ce que tu as un exemple plus complet, réel pour décrire le problème ?

J'ai mis un exemple plus haut mais plus concrètement : la mosaïque sur les éco gestes contient `gestes . bonus stop pub`. gestes est `non applicable` sous certaines conditions donc `bonus stop pub` n'est pas calculé alors que c'est la valeur d'une action applicable justement quand la mosaïque ne l'est pas

**Comment by Clemog** [comment]
Je réouvre un peu le sujet ;)

> Après, je suis plus au courant de l'implé actuelle, mais dans ton exemple initial, il semble que de toutes façon `c` est calculée. En tout cas son calcul s'affiche dans la doc. Donc il y aurait juste un blocage fait au niveau de l'appel de `a . c` qui retourne `non applicable` car `a` l'est ? Dans ce cas là l'appel via un mécanisme ferait l'affaire sans trop de changements.

Hum, il ne me semble pas que ce soit le cas, à priori tu étais dans un cas particulier de la somme de 2 constante directement dans la formule.

Exemple ici : https://publicodes.vercel.app/document/éocène-placide-putté?target=a%20.%20c

(En supposant que `d` est une question.)

**Comment by Clemog** [comment]
Je me dis aussi qu'on pourrait partir sur un fonctionnement à l'inverse de ce que tu proposes @johangirod en gardant le comportement actuel `par défaut` mais qui force l'applicabilité de règles spécifiées ? Implicitement, le mécanisme serait un recalcul dans lequel on rend la variable qui rend la règle non applicable, applicable ou bien il y a un fonctionnement plus simple ?

```
a:
  applicable si: b
  rend non applicable: a . *
  
a . b:
  question: oui ou non ? 
  par défaut: non
  
a . c:
  titre: la règle que l'on veut appeler ailleurs
  

```

(Dans l'exemple [ici](https://publi.codes/studio/c-prime#a%3A%0A%20%20applicable%20si%3A%20b%0A%23%20%20rend%20non%20applicable%3A%20a%20.%20*%0A%20%20%0Aa%20.%20b%3A%0A%20%20question%3A%20oui%20ou%20non%20%3F%20%0A%20%20par%20défaut%3A%20non%0A%20%20%0Aa%20.%20c%3A%0A%20%20titre%3A%20la%20règle%20que%20l'on%20veut%20appeler%20ailleurs%0A%20%20formule%3A%20d%20*%20e%0A%0Aa%20.%20c%20.%20d%3A%205%0A%0Aa%20.%20c%20.%20e%3A%2010%0A%0Ac%20prime%3A%0A%20%20recalcul%3A%0A%20%20%20%20règle%3A%20a%20.%20c%0A%20%20%20%20avec%3A%0A%20%20%20%20%20%20a%20.%20b%3A%20oui), on a bien la valeur de c dans c prime)
