### ISSUE TITLE
Supprimer les "variables traversées"

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#422]
Les "variables traversées" sont utilisées seulement sur mesaidesvelo, les autres applications utilisent les "variables manquantes". Le temps de calcul de ces attributs n'est pas négligeable, et il faudrait donc n'en garder qu'un. Vu les usages actuels, conserver les variables manquantes et supprimer les variables traversées est l'approche du moindre effort.

Je pense toujours que la liste des variables traversées dans l'ordre où elles sont rencontrées est conceptuellement plus simple que l'objet des variables manquantes dont la spécification m'a toujours parue plus compliquée. L'autre problème était que pour afficher une liste de questions utiles à un calcul, la question disparaît de la liste des variables manquantes dès qu'une réponse est ajoutée à la situation, ce qui oblique à gérer un état à côté de la liste retournée par publicodes — alors qu'elle apparaît dans la liste des variables utilisées qu'une réponse est été donnée ou non.

### Alternative

Aller au bout de la logique des variables traversées, et re-implémenter les variables manquantes à partir des variables traversées, afin d'éviter le double calcul traversées / manquantes. J'imagine qu'il y avait quelques difficultés à l'époque où je m'y étais essayé.

**Comment by johangirod** [comment]
Les variables traversées sont utilisées également dans la documentation pour récupérer la situation minimale à donner au moteur pour retomber sur la même valeur que celle affichée : 

Cf [`function buildSituationUsedInRule<Names extends string>`](https://github.com/publicodes/publicodes/blob/70ac101ded3b75b8f9b894ea475bf97b90bf3fb8/packages/react-ui/source/rule/RulePage.tsx#L271-L296)

C'est une fonctionnalité assez pratique, ce serait dommage de s'en passer. 

>  J'imagine qu'il y avait quelques difficultés à l'époque où je m'y étais essayé.

Je me souviens aussi que ça n'avait pas abouti, mais je n'ai plus en tête la raison. J'imagine qu'en faisant un peu d'archéologie on pourrait retomber sur la PR en question :)

**Comment by johangirod** [comment]
J'ai opté pour un compromis à base d'option d'évaluation : par défaut les variables traversées ne sont pas calculées. J'ai également enlevé la section de la doc. On pourra prendre la décision de les enlever complètement sans faire de breaking. Ou de les réimplémenter (ce qui serait la bonne approche IMHO).

cf [0a55dad](https://github.com/publicodes/publicodes/pull/432/commits/0a55dad75017a50bcfbe44f04777e5156bdb3f00)
