### ISSUE TITLE
Site https://publi.codes down

### ISSUE THREAD

**Issue by jonathanfallon** [publicodes/publicodes#426]
Aucune page de fonctionne.
Testé sur Firefox (linux), Firefox (Android), `curl` (linux)

![image](https://github.com/publicodes/publicodes/assets/1656255/55d11031-76e3-498b-9b08-3cfb464976f8)

**Comment by johangirod** [comment]
Bizarre, j'ai relancé un deploy et le problème est parti. A suivre :eyes:
