### ISSUE TITLE
L'égalité de dates ne fonctionne pas comme attendu

### ISSUE THREAD

**Issue by pierrecamilleri** [publicodes/publicodes#430]
Hello, 

### Comportement observé

```yaml
date du jour: 20/12/2023
date à tester: 20/12/2023

est aujourd'hui: date à tester = date du jour
# Valeur : non
```

[Bac à sable](https://publi.codes/studio/est-strictement-dans-le-futur#date%20du%20jour%3A%2020%2F12%2F2023%0A%0Adate%20%C3%A0%20tester%3A%2020%2F12%2F2023%0A%0Aest%20aujourd'hui%3A%20date%20%C3%A0%20tester%20%3D%20date%20du%20jour%0A%23%20Valeur%20%3A%20non%0A%0Aest%20dans%20le%20pass%C3%A9%3A%20date%20%C3%A0%20tester%20%3C%3D%20date%20du%20jour%0Aest%20strictement%20dans%20le%20pass%C3%A9%3A%20date%20%C3%A0%20tester%20%3C%20date%20du%20jour%0A%0Aest%20dans%20le%20futur%3A%20date%20%C3%A0%20tester%20%3E%3D%20date%20du%20jour%0Aest%20strictement%20dans%20le%20futur%3A%20date%20%C3%A0%20tester%20%3E%20date%20du%20jour)

### Comportement attendu

Je m'attendrais à ce que la règle `est aujourd'hui` soit évaluée à "oui".

### Autres détails 

Les autres comparaisons (`<`, `<=`, `>`, `>=`) fonctionnent comme attendu. 

Est-ce un bug ?

**Comment by johangirod** [comment]
C'est un bug :)
