### ISSUE TITLE
Performances v1

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#433]
Bonne année 2024 ! 

J'ai l'impression que la v1 est plus lente que les versions beta ? 

Je compare https://2845--mon-entreprise.netlify.app/simulateurs/salaire-brut-net (publicodes beta) et https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net (publicodes v1), avec les outils de la console du navigateur je trouve +9% pour calculer un salaire median, mais mon ressenti sur mobile est supérieur à cette différence.

Sur https://mesaidesvelo-git-publicodes-v1-novaways.vercel.app/ (publicodes v1) la différence de performance est aussi sensible.

**Comment by johangirod** [comment]
J'observe entre 1% et 6% de temps en plus pour calculer un salaire médian d'après mes mesures (bench, firefox et chrome avec throttle CPU). 

En revanche, j'ai de manière consistante de bien meilleures performances pour le calcul d'une rémunération à partir d'un CA pour un indépendant (entre 10 % et 50 % plus rapide). De même, le parsing des règles est bien plus rapide que dans les versions précédentes.

Il faudrait réussir à comprendre les cas où les performances sont légèrement dégradées, afin de corriger cela. Je n'ai pas réellement de pistes pour le moment. 

Un autre compromis serait de trouver une nouvelle optimisation qui efface ce différentiel.

**Comment by mquandalle** [comment]
J'ai l'impression que la perte de performance que je percevais sur mesaidesvelo ne venait pas de la mise à jour de publicodes en elle-même. Je ne mesure pas de différence significative, je ferme.
