### ISSUE TITLE
Gestion des années bissextile

### ISSUE THREAD

**Issue by Viczei** [publicodes/publicodes#436]
Bonjour,

il semblerai que les conversions de jour/année ou mois/année ne tiennent pas compte des jours supplémentaires des années bissextile.
En effectuant un calcul de durée de 01/01/2010 à 01/01/2024 je m'attendrai à obtenir un résultat de 14 ans hors j'obtiens 14,01 ans.

Un exemple sur le bac à sable: https://publi.codes/studio/anciennet%C3%A9#date%20de%20d%C3%A9but%20de%20contrat%3A%0A%20%20titre%3A%20Quelle%20est%20la%20date%20de%20d%C3%A9but%20du%20contrat%20de%20travail%0A%20%20valeur%3A%2001%2F01%2F2010%0A%0Adate%20de%20fin%20de%20contrat%3A%0A%20%20titre%3A%20Quelle%20est%20la%20date%20de%20fin%20du%20pr%C3%A9avis%20de%20licenciement%20(date%20de%20fin%20du%20contrat)%0A%20%20valeur%3A%2001%2F01%2F2024%0A%0Aanciennet%C3%A9%3A%0A%20%20dur%C3%A9e%3A%0A%20%20%20%20depuis%3A%20date%20de%20d%C3%A9but%20de%20contrat%0A%20%20%20%20jusqu'%C3%A0%3A%20date%20de%20fin%20de%20contrat%0A%20%20unit%C3%A9%3A%20an%0A

**Comment by mquandalle** [comment]
https://github.com/publicodes/publicodes/blob/8e4ae67b4d46a1b9c7578cd36e7c8ada5950fbe0/packages/core/src/date.ts#L74-L77
