### ISSUE TITLE
🐛 La valeur renseignée dans la situation ne semble pas toujours prise en compte dans les "recalcul"

### ISSUE THREAD

**Issue by Clemog** [publicodes/publicodes#469]
J'aimerais ajouter un exemple du bac à sable mais j'ai l'impression que ce n'est pas possible d'hydrater la situation ?

Je pense que c'est reproductible avec [cet exemple,](https://publi.codes/studio/a/c#a%3A%0A%20%20formule%3A%2010%20*%20b%0A%0Aa%20.%20b%3A%0A%20%20question%3A%20Combien%20%3F%0A%0Aa%20.%20c%3A%0A%20%20valeur%3A%20a%0A%20%20contexte%3A%0A%20%20%20%20b%3A%2010%20*%20b) en ajoutant une valeur à b dans la situation.

Mon souci dans l'exemple: si je mets une valeur par défaut pour `a . b`, même avec une valeur de b différente dans la situation, le recalcul prend en compte "l'ancienne" valeur de b

**Comment by Clemog** [comment]
@johangirod J'ai normalement ajouter un test qui casse "comme il faut" 😅 (je ne sais pas si c'était au bon endroit)
https://github.com/publicodes/publicodes/pull/470

**Comment by Clemog** [comment]
Oups, j'avais une erreur, je ne reproduis pas dans le test...

**Comment by Clemog** [comment]
Bon je m'en sors pas, peut-être qu'on pourra regarder ensemble dans la doc NGC comme la dernière fois ..

**Comment by Clemog** [comment]
![exemple](https://github.com/publicodes/publicodes/assets/55186402/7bd37591-2949-4c4e-81bb-18eefe3aed12)

**Comment by Clemog** [comment]
La situation passe de 
```json
{
  "transport . voiture . véhicule récent": "non",
  "transport . voiture . gabarit": "'moyenne'",
  "transport . voiture . thermique . consommation aux 100": "8",
  "transport . voiture . motorisation": "'thermique'",
  "transport . voiture . km": "3000",
  "transport . voiture . utilisateur régulier": "oui"
}
```

à 

```json
{
  "transport . voiture . véhicule récent": "non",
  "transport . voiture . gabarit": "'moyenne'",
  "transport . voiture . thermique . consommation aux 100": "8",
  "transport . voiture . motorisation": "'thermique'",
  "transport . voiture . utilisateur régulier": "oui",
  "transport . voiture . km": "voiture . km * (1 - 0.41)"
}
```

**Comment by Clemog** [comment]
##⚠️ EDIT

Punaaaaise je crois que tout fonctionne ! J'avais un souci de version de publicodes, c'est bien corrigé avec la dernière release, je suis désolé pour le spam 🤦‍♂️

**Comment by mquandalle** [comment]
@Clemog Une idée pour éviter ce type de déconvenues : afficher la version de publicodes dans la documentation #472
