### ISSUE TITLE
[react-ui] Choix du nombre de décimale pour l'affichage des arrondis par règle

### ISSUE THREAD

**Issue by eweap** [publicodes/publicodes#479]
Le component react affiche les valeurs arrondies au centième (ce qui est suffisant dans la majorité des cas)
![image](https://github.com/publicodes/publicodes/assets/1033191/ab824825-225b-44b8-b93b-5d26d54cbf20)

Mais dans certains cas, comme par exemple pour la règle [`salarié . cotisations . APEC . salarié`](https://github.com/betagouv/mon-entreprise/blob/2599d46bdc28d6e05004ea52db47c2e68417bfaa/modele-social/r%C3%A8gles/salari%C3%A9/cotisations.publicodes#L609), il est important d'afficher l'arrondi au millième, sinon le résultat affiché parait erroné.

Est-il possible de forcer l'affichage avec un arrondi au millième, sinon, quelles modifications sont envisageables ?

Merci d'avance.

**Comment by johangirod** [comment]
> Est-il possible de forcer l'affichage avec un arrondi au millième, sinon, quelles modifications sont envisageables ?

Effectivement, c'est impossible dans l'immédiat, mais c'est une fonctionnalité qui aurait tout à fait sa place. 

Il est possible de « ruser » en n'apposant pas d'unité mais ce n'est pas satisfaisant : 
```
foobar: 
  valeur: 0.0024232
  unité: "%"
 ```

On pourrait imaginer plusieurs pistes pour répondre au problème : 
- Ajouter des méta « affichage » dans la règle publicodes qui contiennent des informations sur la précision à afficher (entre autres)
- Utiliser la valeur du mécanisme `arrondi` si il existe
- Avoir un mécanisme de mise en forme directement dans publicodes #403

**Comment by mquandalle** [comment]
Une approche discutée [jadis](https://github.com/publicodes/publicodes/issues/148#issuecomment-1023069389) mais pas implémenté, c'était de gérer cela automatiquement via le décompte et l'inférence des chiffres significatifs (= du nombre de décimales). Ceci dit pour les valeurs littérales comme dans l'exemple initial le fait de garder la précision du nombre saisi était géré avant mais ça s'est sans doute perdu dans une modification du code.

**Comment by liliced** [comment]
Je relance le sujet car j'ai également rencontré le problème. Dans les règles de la réduction générale des cotisations patronales, nous travaillons avec des coefficients à 4 décimales.
Pour les calculs, l'arrondi semble respecté car le résultat final est correct.
En revanche la documentation n'affiche le coefficient qu'avec 2 décimales (`0,2597` est affiché `0,26` dans la doc)

J'ai contourné le problème en affichant le coefficient sous forme de pourcentage (`25,97%` dans l'exemple) mais je perds en cohérence avec les autres sources qui utilisent cette valeur et qui affichent `0,2597`.

Parmi les solutions proposées, l'usage de la valeur du mécanisme `arrondi` me semble être la plus pertinente. Imho cela est à la fois le plus simple (pas de champ supplémentaire à renseigner) et le plus transparent (la documentation reprend exactement les valeurs utilisées pour les calculs).

**Comment by johangirod** [comment]
@liliced, j'ai oublié de le noter, mais cette issue a normalement été réglée dans la dernière version de publicodes.
#548
