### ISSUE TITLE
Éditeur v2

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#488]
- [x] Réimplémenter la logique d'affichage de la documentation ;
- [x] Ajouter les messages d'erreur ;
- [x] Fusionner le studio et l'éditeur `inline` de la doc ;

**Comment by Clemog** [comment]
Je suis pas sur de bien comprendre l'objet de l'issue ? 😇

**Comment by johangirod** [comment]
C'est de créer un nouvel éditeur online pour publicodes en Svelte. J'ai déjà bien avancé, tu peux tester sur la branche website-v2, je l'ai intégré sur la landing :)

Il manque plus que les messages d'erreur et le branchement avec l'URL dans publicodes studio.

**Comment by mquandalle** [comment]
Wouah il y a une v2 du site en Svelte ?!

**Comment by johangirod** [comment]
Haha oui, j'ai hésité à modifié docusaurus, et en fait, c'est tellement galère d'ajouter des comportements custom, je me suis dit que ça prendrait moins de temps et d'energie de le refaire en svelte.

Et en plus ça serait beaucoup plus fun.
