### ISSUE TITLE
Liste des paquets publicodes

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#489]
Créer une page `/bibliotheques` qui liste tous les paquets publicodes. 

## Données
Pour commencer, la source de donnée pourrait être un JSON / JS / YAML avec les champs suivants : 
- `nom`
- `slug` / `id`
- `description`
- `lien`
- `réutilisateurs` : ? `<slugProjet>` (cf #491)
- `mainteneur` : `<slugProjet>` (cf #491)
- ? `api` : lien vers le swagger de l'api
- ? `npm` : lien vers le paquet npm

L'idée est de relier la bibliothèque de règle à tous les projets qui l'utilise. 

## UI

- Nom
- Utilisé par : liste de lien vers les projets / avec logo du projet si existant, sinon celui de l'administration.
- Édité par : logo + nom 
Le mainteneur sera mis en avant en affichant les informations derrière la clé `author` du projet

**Comment by Clemog** [comment]
@EmileRolley tu souhaitais prendre celle ci c'est ça ?

**Comment by EmileRolley** [comment]
> @EmileRolley tu souhaitais prendre celle ci c'est ça ?

Oui mais si tu souhaites t'en occuper vas-y, j'ai d'autre issues à traiter :)

**Comment by Clemog** [comment]
> Oui mais si tu souhaites t'en occuper vas-y, j'ai d'autre issues à traiter :)

Nope c'était pour t'assigner 😈
