### ISSUE TITLE
Nouveau studio : tabulation ne fonctionne pas

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#508]
Sur la preview du [nouveau studio](https://publicodes-website-v2-git-doc-v2-add-url-sharing-publicodes.vercel.app/studio) un appui sur <kbd>Tab</kbd> n'insère pas une tabulation comme attendu.

Macos / Navigateur Arc

**Comment by johangirod** [comment]
C'est réparé, au temps pour moi.
