### ISSUE TITLE
Ajouter un mécanisme `puissance`

### ISSUE THREAD

**Issue by pbourdu** [publicodes/publicodes#529]
**User story**
En tant que modélisateur, je souhaite pouvoir réaliser des calculs de mathématiques financières simples.

**Détails**
La syntaxe `^` est déjà utilisé pour la référence aux règles antécédentes.
Nous pourrions utiliser [la syntaxe `**`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Exponentiation)

Exemple de notation dans un calcul d'intérêts composés sur un capital placé : `Cn = C * ( 1 + i ) ** n`
Avec : 
- `Cn` le capital acquis en période `n`
- `C` le capital placé
- `i` le taux d'intérêts (0.02 équivalent à 2%)
- `n` le nombre de périodes

**Exemple**
Ex., 100 placé à 2% pendant 3 périodes.
- `C1` = `102`
- `C2` = `104.04`
- `C3` = `106.12` équivalent à `100 * ( 1 + 2% ) ** 3`

**Comment by pbourdu** [comment]
@johangirod, je soumets cette évolution (qui ressemble beaucoup à #525 ). Je suis partant pour tenter le développement si ma proposition est conforme ?

**Comment by Clemog** [comment]
Bravo !
