### ISSUE TITLE
Disparaition de la page de doc du SDK javascript new Publicodes()

### ISSUE THREAD

**Issue by laem** [publicodes/publicodes#565]
Sur l'ancien site, il y avait une page qui faisait ça. 
La ref est toujours présente sur le README du paquet NPM, vers la 404 https://publi.codes/docs/api/core

J'y cherchais la documentation du mode script décrit dans le Changelog. 

Est-ce volontaire, ou juste une page qui a sauté ?

**Comment by johangirod** [comment]
> Est-ce volontaire, ou juste une page qui a sauté ?

En fait, un peu des deux :sweat_smile: 

Le but était d'implémenter #482 dans la foulée de la migration, mais on a été pris sur d'autres sujets. 

À remettre en haut des priorités, donc.

**Comment by EmileRolley** [comment]
Je pense que l'on peut fermer la discussion (voir https://publi.codes/docs/api/publicodes)
